[14.0][IMP] account_payment_order: added bill date to Create Transactions wizard
OCA/bank-payment pull request #1034
Opened 2023-02-10 13:08 UTC by dalonsod

Some customers find useful bill date to be shown in Select Move Lines to Create Transactions wizard form, this PR simply adds it.

2023-02-10 13:16 UTC, dalonsod commented
@mtbochaca could you review? Thanks!

2023-02-10 13:24 UTC, dalonsod commented
@dannyadair could you review? Thanks!

2023-02-16 09:29 UTC, dalonsod commented
@dannyadair @pedrobaeza could you review? Thanks!

2023-03-02 08:07 UTC, dalonsod commented
@ChristianSantamaria @lmiguens-solvos could you review? Thanks!

2023-03-02 08:25 UTC, ChristianSantamaria approved these changes
LGTM 👍

2023-03-02 10:42 UTC, lmiguens-solvos approved these changes
LGTM

2023-03-02 12:01 UTC, dalonsod commented
@pedrobaeza is this PR ready to be merged? When done, I'll make the fw-port to v15

2023-03-02 12:44 UTC, pedrobaeza commented
This needs a PSC review. I'm not able to do it right now, sorry.

2023-03-02 12:49 UTC, dalonsod commented
@HaraldPanten could you review? Thanks!

2023-03-02 12:57 UTC, pedrobaeza reviewed
I have made a quick review, and adding such related field drains performance on the tree, as it needs to be extracted for each line, so I'm not sure this is convenient.

2023-03-02 14:51 UTC, dalonsod commented
Yes, I've simply used a related non-stored field because the expected list of moves to be shown in that tree view shouldn't be a large one. And that field is not intended to be used in other views.

Anyway, if this field could be dangerous, it could be solved making it `store=True` + pre-migration script, is it right?

2023-03-02 14:54 UTC, pedrobaeza commented
Not really, that would be worse, as on installation/update, existing lines will need to store the value.

It will also be confused for move lines not coming from invoices, or redundant on customer invoices. It seems a very specific need that shouldn't go on standard IMO.

2023-03-02 19:12 UTC, gdgellatly commented
Agree with @pedrobaeza , the practice of having a different invoice and move date is very very rare.

This from a midsized database, subject to IFRS, say 3 years old doing vanilla Odoo.

```
devel=# SELECT count(*) FROM account_move WHERE invoice_date != date AND invoice_date IS NOT NULL;
 count 
-------
   158
(1 row)

devel=# SELECT count(*) FROM account_move WHERE invoice_date IS NOT NULL;
 count  
--------
 786057
(1 row)
```

2023-03-02 19:22 UTC, gdgellatly requested changes
See general comments in PR, if anything in a standard installation it will do more to confuse users than help them. and is mostly redundant anyway because by default, the accounting date and invoice date are the same. I think if you face a situation where this isn't the usual case, probably best addressed in a separate module, possibly more completely rather than show 2 dates.

2023-03-02 19:44 UTC, dalonsod commented
Thanks a lot for the comments @gdgellatly !

I have not problem creating a custom addon for this. I've simply make this improvement here because I've got some customers with such requirement (one of them has 99% of vendor bills in this situation) and I thought that it could be useful for other people.

Anyway, preventing that `invoice_date` wanted to be used by a few users, I've made the field `optional="hide"` in the view.

As @pedrobaeza said, if performance could be affected for the current functionality, no need to continue this way. Then, closing this.

2023-03-02 19:44 UTC, closed without merging