[15.0][MIG] account_invoice_select_for_payment:migration module
OCA/bank-payment pull request #1090
Opened 2023-06-05 11:56 UTC by valjaro

2023-06-06 10:46 UTC, polqubiq approved these changes
LGTM

2023-06-26 15:46 UTC, kaynnan requested changes
Change the commit history [[[ADD] account_invoice_select_for_payment: Migration to 15](https://github.com/OCA/bank-payment/pull/1090/commits/938bf9754b9c9fdbcb67fb1c72a6d0c6613d8128)](https://github.com/OCA/bank-payment/pull/1090/commits/938bf9754b9c9fdbcb67fb1c72a6d0c6613d8128) you are performing a migration, so please use the tag [MIG] and not [ADD].

2023-07-13 09:29 UTC, kaynnan approved these changes

2023-11-29 15:27 UTC, florian-dacosta commented on account_invoice_select_for_payment/models/account_payment.py
> -        return super().action_register_payment()
Why removing this line, I don't get it.

2024-08-25 12:16 UTC, closed without merging