[16.0] account_payment_order: re-implement allow_blocked
OCA/bank-payment pull request #1150
Opened 2023-09-27 21:29 UTC by alexis-via

allow_blocked has been moved from the wizard that adds payment lines to the payment mode. That way, users cannot modify it. And they cannot by-pass it by using the button "add to payment order" on the invoice. The 'blocked' status is also check upon confirmation of the payment order (in case it has been marked as blocked AFTER being added to the payment order).

2023-09-27 21:37 UTC, alexis-via commented
If you need this on v14, it is integrated in this PR: https://github.com/OCA/bank-payment/pull/1149

2023-09-28 06:19 UTC, pedrobaeza requested changes
I don't see this as an improvement, but a regression, as my users want to be able to select if they want to include them or not. You shouldn't remove it from the wizard, although you can add an extra option at payment mode level with 3 levels: yes, no or selectable, and act in consequence.

2023-09-28 14:17 UTC, jdidderen-noviat reviewed
I'm a bit puzzled about this change. 

On one hand, I can see this as an improvement for people who wants to have more protections around this flag.

On the other hand, I also agree with Pedro that it can be see as a degression for some people.

An idea would be to have it computed at the payment order level based on the payment mode (in readonly = false and invisible) and keep the flag in the wizard so the user can change the flag on the payment order from the wizard. And hide the flag in the wizard behind a security groups or something like that in order of having both approaches working

2023-09-28 14:19 UTC, pedrobaeza commented
The three-valued selection I suggested can be compatible with this last suggestion: on payment mode, you decide which behavior for allow_blocked:

- Selectable. The default one. Everything continues the same, having it in the wizard.
- Yes. You allow them without asking.
- No. You don't allow them.

2023-09-29 22:42 UTC, alexis-via commented
Taking into account your comments, I changed the implementation:
Option "allow_blocked" on payment mode:
- if False : ALWAYS block, no workaround possible: blocked when trying to push an invoice on a payment order, block in the wizard to pull move lines on payment order (no option displayed to user), block upon confirmation of payment order
- if True : No systematic blocking. Show the option "allow_blocked" in the wizard, to give the option to the user to select blocked move lines if he wants to.

2023-09-30 19:06 UTC, jdidderen-noviat approved these changes
Thanks for the changes :)
LGTM

2023-10-03 09:02 UTC, houzefa-abba approved these changes

2023-10-03 13:59 UTC, pedrobaeza commented
For UX, I still prefer the three-value option. If not, people get confused about what means not having "Allow block" checked.

2023-11-03 22:52 UTC, alexis-via commented
I really prefer a solution with 2 possibilities instead of 3. The third option "allow without asking" doesn't make sense to me. It undermines the importance of having a litigation with a supplier (or a customer).

2023-11-04 10:39 UTC, pedrobaeza commented
Please check again my comment. I haven't said in any moment "allow without asking". The options are:


* Selectable. The default one. Everything continues the same, having it in the wizard.
* Yes. You allow them without asking.
* No. You don't allow them.

2023-11-04 10:42 UTC, pedrobaeza commented
The "yes" option makes sense to me, but if not, another rephrasing should be done for the boolean. You can put a selection with 2 options then.

2023-11-06 12:08 UTC, luc-demeyer approved these changes

2024-04-14 14:37 UTC, closed without merging