[IMP] Allow to use the storage either from the payment mode or from the payment method
OCA/bank-payment pull request #1279
Opened 2024-05-31 07:55 UTC by lmarion-source

Initially, the storage was found only on the payment method. We added the storage at the payment mode level to allow different storage for different companies.

2024-05-31 09:01 UTC, AnizR requested changes
Great initiative :+1:

2024-05-31 09:01 UTC, AnizR commented on account_payment_method_or_mode_fs_storage/models/account_payment_mode.py
> +            self.env["fs.storage"].sudo().search([("use_on_payment_method", "=", True)])
I think that it should be 'use_on_payment_mode'?

2024-05-31 09:01 UTC, AnizR commented on account_payment_method_or_mode_fs_storage/tests/test_account_payment_method_or_mode_fs_storage.py
> +        self.company.update(
I think that you need to adapt the test to change the 'source' of the fs_storage

2024-05-31 09:02 UTC, AnizR commented
@acsonefho ping

2024-05-31 13:39 UTC, acsonefho requested changes

2024-05-31 13:39 UTC, acsonefho commented on account_payment_method_or_mode_fs_storage/models/fs_storage.py
> +    use_on_payment_mode = fields.Boolean(
As discusses, IMO it's not a good idea to always adding a boolean on the storage itself to know where it should be available.
The idea is to add (into config) which storage are available for payment mode (and same for payment method).
The `use_on_payment_mode` shouldn't be an attribute of the storage.

2024-05-31 13:39 UTC, acsonefho commented on account_payment_method_or_mode_fs_storage/models/account_payment_mode.py
> +            self.env["fs.storage"].sudo().search([("use_on_payment_mode", "=", True)])
I suppose this should be updated with my previous comment

2024-05-31 13:39 UTC, acsonefho commented on account_payment_method_or_mode_fs_storage/models/account_payment_order.py
>          export_storage = self.env["fs.storage"].sudo().search([("id", "=", storage_id)])
Please can you use a `browse(storage_id)`.
Both are the same but technically, the `browse` could use the existing cache/prefetch and `search` force using a `flush` (on specific columns) who is not necessary.

2024-05-31 13:39 UTC, acsonefho commented on account_payment_method_or_mode_fs_storage/models/fs_storage.py
> +        storage_not_on_payment = self.filtered(lambda r: not r.use_on_payment_mode)
Based on my previous comment, I suppose this should be moved too.

2024-05-31 13:39 UTC, acsonefho commented on account_payment_method_or_mode_fs_storage/models/res_company.py
> +    fs_storage_source_payment = fields.Selection(
IMO this is strange. It depends on where the storage is filled.
That means `mode` and `method` can not be mixed?

2024-06-14 07:54 UTC, acsonefho requested changes

2024-06-14 07:54 UTC, acsonefho commented on account_payment_method_or_mode_fs_storage/migrations/16.0.1.0.4/post-migrate.py
> +    openupgrade.update_module_names(env.cr, modules, merge_modules=True)
I'm not sure about `merge_modules=True`.

2024-06-14 07:54 UTC, acsonefho commented on account_payment_method_or_mode_fs_storage/models/account_payment_method.py
> +    def write(self, values):
Useless

2024-06-14 07:54 UTC, acsonefho commented on account_payment_method_or_mode_fs_storage/models/account_payment_order.py
> +        return self.payment_method_id.storage
IMO you should do a `else` section.
And if doesn't fit to your case: `return ''` (in case of another module extend your `fs_storage_source_payment`.

2024-06-14 07:54 UTC, acsonefho commented on account_payment_method_or_mode_fs_storage/models/account_payment_order.py
>          export_storage = self.env["fs.storage"].sudo().search([("id", "=", storage_id)])
up :pray:

2024-06-14 07:54 UTC, acsonefho commented on account_payment_method_or_mode_fs_storage/models/res_config_settings.py
> +        res = super(ResConfigSettings, self).get_values()
More python 3: `super().get_values()`

2024-06-14 07:54 UTC, acsonefho commented on account_payment_method_or_mode_fs_storage/models/res_config_settings.py
> +        return super(ResConfigSettings, self).set_values()
More python 3: `super().set_values()`

2024-06-14 07:54 UTC, acsonefho commented on account_payment_method_or_mode_fs_storage/readme/CONTRIBUTORS.rst
You're a contributor :muscle:

2024-06-14 11:35 UTC, acsonefho approved these changes

2024-06-17 13:25 UTC, acsonefho approved these changes

2024-06-19 09:45 UTC, acsonefho approved these changes

2024-12-01 12:21 UTC, closed without merging