[14.0][IMP] account_payment_order: Fix dates in payments
OCA/bank-payment pull request #1328
Opened 2024-08-05 10:19 UTC by Raul-S73

The date of payments is corrected because the date on which the payment order is confirmed is currently established
This means that payments are not grouped correctly.

Before:
![image](https://github.com/user-attachments/assets/51c321da-1ba0-47b9-a9b2-f05c1583a94f)

With this changes:
![image](https://github.com/user-attachments/assets/a1a3f3de-49ac-4fc2-b35d-13a6e112b359)

Before:
![image](https://github.com/user-attachments/assets/68ac5fb5-03e0-4011-95ad-26c933323ee3)

With this changes:
![image](https://github.com/user-attachments/assets/70fea33a-dd5d-4d34-8bcd-f6d171ec6e90)

2024-08-05 10:23 UTC, pedrobaeza requested changes
This was changed on purpose on #1305 and #1311

2024-08-05 10:35 UTC, Raul-S73 commented
@pedrobaeza
How are payments going to be grouped if the due date is always the date on which the collection order is confirmed?
If I want to have payments grouped by due date, how do I do it?

2024-08-05 10:37 UTC, pedrobaeza commented
You should change the grouping criteria in the other module then.

2024-08-05 10:38 UTC, pedrobaeza commented
Anyway, if I don't remember bad, the *_grouped_output module groups everything together without more criteria.

2024-08-06 13:18 UTC, Raul-S73 commented
@pedrobaeza 

Hello again, 
I have done this PR due to the needs of our clients.
When they place the payment order until now they were grouped by the due date, this way they had everything more under control. Now there is no possibility to group that way. 

With these changes, it returns to grouping by due date, making the groupings in the payment order.

2024-08-06 13:20 UTC, pedrobaeza requested changes
It was incorrect before, not following the accrual principle. If your customer wants such grouping, I think you must change it at the grouping module, or in your custom.

2024-09-12 08:26 UTC, gdgellatly commented
@pedrobaeza @Raul-S73 This is also a big problem for us. With fixed execution date even, you get the date of confirmation and not the fixed date you proposed. It really is not intuitive, but seeing it won't be changed we will just put in own module.

2024-09-12 09:20 UTC, pedrobaeza commented
As said, that way of working is not correct in accounting terms. It's just like Odoo, that worked a lot of time wrongly posting entries directly in the bank account when you register a payment, and now it works correctly.

2024-09-12 10:24 UTC, gdgellatly commented
cmon @pedrobaeza I am a chartered accountant, so I don't need telling what is correct in accounting terms. It is absolutely correct to show a payment at the date it is paid. whether that is tomorrow or in 6 months time. It is extremely common and every accountant knows this.

2024-09-12 10:25 UTC, pedrobaeza commented
The question is that this is not a payment, it's the promise of a future payment. That's why the journal entry date + due date has been adjusted this way.

2024-09-12 10:25 UTC, gdgellatly commented
Just to follow this up by way of example. I have a balance date of 31 December, and a fixed payment going on 1st Jan. By you argument, the financial year it should appear is whether I do it on the 31st or 1st? complete nonsense to say that a confirmation date is an accounting date.

2024-09-12 10:29 UTC, pedrobaeza commented
On the 31st of December, you have the balance in the outstanding receipt. On the 1st of January, when coming to your bank, you neutralize the outstanding receipt, and have it on the bank account.

What is not correct is to have all the outstanding receipt balance, its neutralization, and the bank balance on the 1st of January.

2024-09-12 10:30 UTC, gdgellatly commented
> On the 31st of December, you have the balance in the outstanding receipt. On the 1st of January, when coming to your bank, you neutralize the outstanding receipt, and have it on the bank account.
> 
> What is not correct is to have all the outstanding receipt balance, its neutralization, and the bank balance on the 1st of January.

It is a January payment not a december payment, anyway I can't be bothered arguing standard accounting practice going back to the days of postdated cheques. You are right, we will just be wrong somewhere else.

2024-09-12 10:33 UTC, pedrobaeza commented
Well, I'm trying to understand any use case outside of the common ones to check for inconsistencies. Till now, we haven't found any. I don't get if your last comment is irony, or I'm missing some detail being English my foreign language.

2024-09-12 10:36 UTC, gdgellatly commented
It just means it is not a fight worth having when I can add to a custom module in 5 minutes. The use case is simple. It is not a promise of a future payment, it is a plan to pay on a certain date. Now I might understand if we were talking about customer payments, but if you are trying to do any cashflow planning even then I think it is unwise to not record at the correct date, but for suppliers no such promise exists. It is simply a future dated transaction.

2024-09-12 10:48 UTC, pedrobaeza commented
Well, I think any cashflow forecasting should be done using the due date, not the accounting date. It's the same case as with invoices: you have the entry date on the day you post the invoice, but the due date specifies when it should paid/debt.

2024-09-12 20:01 UTC, gdgellatly commented
As I say, I completely disagree, the issue was raised by internal audit, a team of 4 accountants prior to external audit.  A fixed execution date is the payment date. But not worth the fight, we fixed it where it needs fixing and everyone can be happy.

2025-01-12 14:25 UTC, closed without merging