[16.0][IMP] Take allow_out_payment into account on payment order
OCA/bank-payment pull request #1340
Opened 2024-08-29 13:15 UTC by lmarion-source

A previous MR existed but only when payment order was triggered from invoices.
We added the case also directly from confirm button on payment order

2024-08-30 05:22 UTC, acsonefho requested changes
GJ :muscle: 
Just a minor change :pray:

2024-08-30 05:22 UTC, acsonefho commented on account_payment_order/models/account_move.py
> +                line._check_bank_allows_out_payments()
As you already loop in your function, you can skip one level:
`applicable_lines.filtered(lambda l: l.account_id.account_type == "liability_payable")._check_bank_allows_out_payments()`

2024-08-30 12:30 UTC, acsonefho approved these changes

2024-09-12 06:41 UTC, acsonefho approved these changes

2024-09-12 15:17 UTC, adrienpeiffer approved these changes

2024-09-12 15:37 UTC, adrienpeiffer commented
/ocabot merge minor

2024-09-12 15:41 UTC, pedrobaeza requested changes
I have stopped the merge. AFAIK, @sbidoul commented that wants to be able to add the lines, but not to confirm the order, and this is pre-filtering the non-allowed bank accounts previously if I understand the code right.

2024-09-12 15:41 UTC, pedrobaeza commented on account_payment_order/models/account_move.py
> +
Please don't introduce empty lines inside the method

```suggestion
```

2024-09-12 15:41 UTC, pedrobaeza commented on account_payment_order/models/account_payment_order.py
> +
No empty lines

```suggestion
```

2024-09-12 15:53 UTC, adrienpeiffer commented
@pedrobaeza Not sure to understand. The check id done in draft2open method.

2024-09-12 15:56 UTC, pedrobaeza commented
I mean this code for example:

https://github.com/OCA/bank-payment/pull/1340/files#diff-bb6441f4ea06462fe1aae1f093f82c4e57460864b29b209676a6c7ce14e49ef9R156

It's avoiding to include the lines in the order.

2024-09-12 16:09 UTC, adrienpeiffer commented
Isn't that exactly the code approved in #1177 ?

2024-09-12 16:30 UTC, pedrobaeza commented
OK, I based my review in https://github.com/OCA/bank-payment/pull/1177#issuecomment-2304668141. Let me check again.

2024-09-13 06:57 UTC, adrienpeiffer commented
@lmarion-source Could you remove blank lines (cfr pedro's review)
@sbidoul If I undersood correctly, you prefer to be able to add lines from invoces even bank account is not validated ?
So basically, we have to remove this line https://github.com/OCA/bank-payment/pull/1340/files#diff-bb6441f4ea06462fe1aae1f093f82c4e57460864b29b209676a6c7ce14e49ef9R158

2024-09-13 07:40 UTC, sbidoul commented
> If I undersood correctly, you prefer to be able to add lines from invoces even bank account is not validated ?

It is my impression that Odoo Enterprise works like that, and it makes sense to me, since the process of preparing payment orders is distinct from the process of validating bank accounts, and often done by different persons. So I think it's better to let both processes run in parallel and block at the last moment. Cherry on the cake would be a warning when an non validated bank account is used in a payment line, but that can be done in another PR.

2024-09-13 08:43 UTC, gdgellatly commented
Hmm, we solved this completely differently. I get the minimal touch here, but we made a seperate module that hit all the places Odoo gets this wrong, mostly purchase order and account move but also payment with a single function on bank to get a valid out payment bank account. Then overrode `def _compute_available_partner_bank_ids(self):` which for me seems to be the place this belongs

2025-03-02 13:01 UTC, sbidoul commented
Reopening as I think it needs another review round after the last commits. What's the status of this?

2025-03-10 17:23 UTC, Cedric-Pigeon approved these changes
I like the approach of letting the user making the payment order and block at the end in case of unvalidated account.
I would be really interested to get it merge soon as I'd need to forward-port it to v17.0

2025-03-15 19:29 UTC, Cedric-Pigeon commented
@lmarion-source Could you please resolve conflicts ?

2025-04-30 07:47 UTC, AnizR commented
ping @lmarion-source

2025-04-30 11:25 UTC, AnizR requested changes
Almost good, thanks!

2025-04-30 11:25 UTC, AnizR commented on account_payment_order/models/account_payment_order.py
> +                    ):
```suggestion
                    if str2bool(
                        self.env["ir.config_parameter"]
                        .sudo()
                        .get_param("account_payment_order.use_allow_out_payment")
                    ):
```

2025-04-30 14:13 UTC, AnizR approved these changes
Code LGTM

2025-05-16 13:38 UTC, Cedric-Pigeon approved these changes
LGTM

2025-06-12 09:55 UTC, sbidoul commented
@pedrobaeza can you update your review here?

2025-06-12 09:59 UTC, sbidoul commented on account_payment_order/models/account_payment_order.py
> +                        payline._check_bank_allows_out_payments()
Don't we need to check that `payment_type` is `outbound` here? Because this check does not make sense for a debit order.

2025-06-12 10:00 UTC, sbidoul commented on account_payment_order/models/account_move_line.py
> +        partner_bank_id = self.partner_bank_id or first(self.partner_id.bank_ids)
```suggestion
        partner_bank = self.partner_bank_id or first(self.partner_id.bank_ids)
```

2025-06-21 10:02 UTC, pedrobaeza commented
@lmarion-source can you please check the latest comments?

2025-10-17 16:02 UTC, sbidoul requested changes

2025-10-17 16:02 UTC, sbidoul commented on account_payment_order/wizard/res_config_settings.py
> +        string=" Use allow out payment on partner bank",
```suggestion
        string="Verify that Send Money is enabled on partner bank accounts",
```

Is this easier to understand by non technical users?

2025-10-17 16:02 UTC, sbidoul commented on account_payment_order/wizard/res_config_settings.xml
> +                </div>
This ends up in the next section. Not sure this is fixable in this PR, though.

<img width="550" height="612" alt="Image" src="https://github.com/user-attachments/assets/fa4123f3-3b60-4c4b-8f7a-761678bc36c3" />

2025-10-17 16:02 UTC, sbidoul commented on account_payment_order/models/account_payment_order.py
> +                        payline._check_bank_allows_out_payments()
@lmarion-source I looks like you have not handled this comment?

2025-10-17 16:05 UTC, sbidoul commented
rebased

2026-03-14 04:39 UTC, marcos-mendez approved these changes
**Automated Review -- Tests Passed**

All tests for `account_payment_order` passed successfully on Odoo 16.0.
Environment: Minikube + K8s Job + oca-ci/py3.10-odoo16.0

---
### ⚠️ PR Aging Alert: CRITICAL

This PR by @lmarion-source has been **waiting for 561 days** — that is over **18 months** without being merged or closed.

> _Every ignored PR is a contributor who might not come back. Review time matters. ([OCA Aging Report](https://git.pop.coop/pop/oca-reviewer))_

---
### Reciprocal Review Request



Hi everyone! Thanks for your contribution to OCA. I reviewed and approved this PR. If any of you have a moment, I would really appreciate a review on my open PR(s):

**My open PRs across OCA:**
- [hr-attendance#262 [16.0][ADD] Hr_attendance_idsecure: iDSecure (ControliD) attendance integration](https://github.com/OCA/hr-attendance/pull/262)
- [stock-logistics-workflow#2276 [16.0][ADD] stock_move_line_devaluation](https://github.com/OCA/stock-logistics-workflow/pull/2276)
- [stock-logistics-workflow#2275 [16.0][ADD] Stock move line analytic account](https://github.com/OCA/stock-logistics-workflow/pull/2275)
- [stock-logistics-workflow#2268 [16.0][ADD] stock_move_line_picking_partner](https://github.com/OCA/stock-logistics-workflow/pull/2268)
- [purchase-workflow#2694 [16.0][IMP]Purchase workflow added to review state & exception fix](https://github.com/OCA/purchase-workflow/pull/2694)

Reviewing each other's work helps the whole community move forward faster. Thank you!

---
_Automated review by [OCA Neural Reviewer](https://git.pop.coop/pop/oca-reviewer) + qwen3-coder:30b_

2026-08-23 12:20 UTC, closed without merging

2026-10-26 17:24 UTC, sbidoul commented
rebased, as I still use this