[14.0][IMP] Add warning when payment order is not SEPA
OCA/bank-payment pull request #1344
Opened 2024-09-10 08:05 UTC by toita86

>The field 'sepa' on account.payment.order is only display for SEPA payment methods.
If the option "show warning if not SEPA" is enabled on the payment method, a warning banner is now displayed on payment orders with a SEPA payment method which are not SEPA.

Backporting of https://github.com/OCA/bank-payment/pull/1149 needed for https://github.com/OCA/l10n-italy/pull/4367

2024-09-11 09:49 UTC, anmarmo1 commented
The functional review is correct.
![image](https://github.com/user-attachments/assets/fc84fa5b-cec2-47c0-996c-ef07fc8224b4)

2024-09-11 11:19 UTC, francesco-ooops commented
Thanks @anmarmo1 , could you approve the PR?

@alexis-via @pedrobaeza was there any problem with this feature in v14?

2024-09-11 11:23 UTC, anmarmo1 approved these changes
Yes! sorry

2024-09-11 14:35 UTC, pedrobaeza commented
Second commit is not adding anything.

2024-09-12 08:31 UTC, GSLabIt approved these changes
Maybe you can squash commits? Overall looks good

2024-09-13 07:54 UTC, francesco-ooops commented
@pedrobaeza good to go? :)

2024-09-13 07:55 UTC, pedrobaeza requested changes

2024-09-13 07:55 UTC, pedrobaeza commented on account_banking_pain_base/README.rst
> +* `Ooops404 <https://www.ooops404.com/>`_:
This shouldn't be added, as it's only a cherry-picking

2024-09-13 08:22 UTC, toita86 commented on account_banking_pain_base/README.rst
> +* `Ooops404 <https://www.ooops404.com/>`_:
@pedrobaeza my bad, just fixed!

2024-09-13 08:24 UTC, pedrobaeza approved these changes
/ocabot merge patch

2024-09-13 08:32 UTC, merged