[18.0][MIG] account_payment_mode
OCA/bank-payment pull request #1367
Opened 2024-10-15 11:09 UTC by BertVGroenendael

2024-10-15 11:31 UTC, rvalyi submitted a review, later dismissed
approved

![2024-10-15_11-28](https://github.com/user-attachments/assets/87ba231f-0674-4e63-a48a-ae1ec783e953)

2024-10-24 21:28 UTC, alexis-via requested changes
We first need to decide if we switch account.payment.mode to the new native account.payment.method.line, cf discussion on https://github.com/OCA/bank-payment/issues/1364

2024-10-25 21:58 UTC, alexis-via commented
@BertVGroenendael Don't hesitate to give your opinion on the questions that I raised about the migration to v18 of OCA/bank-payment.

2025-01-22 08:32 UTC, JordiMForgeFlow approved these changes
code + functional 👍🏼 

I agree with @pedrobaeza opinion on keeping the OCA account payment mode (https://github.com/OCA/bank-payment/issues/1364#issuecomment-2472706470). I would maybe hide the Odoo standard fields in `account_payment_partner` module

2025-01-22 08:38 UTC, pedrobaeza commented
/ocabot migration account_payment_mode

2025-01-22 08:38 UTC, pedrobaeza commented on account_payment_mode/views/account_payment_method.xml
> +    <record id="account_payment_method_list" model="ir.ui.view">
Please don't rename the XML-ID for avoiding changes in subsequent modules.

2025-01-22 08:38 UTC, pedrobaeza commented on account_payment_mode/views/account_payment_mode.xml
> +    <record id="account_payment_mode_list" model="ir.ui.view">
The same about the XML-ID

2025-03-04 15:42 UTC, juancarlosonate-tecnativa commented
@BertVGroenendael please check the comments, thx!

2025-03-25 13:36 UTC, carlos-lopez-tecnativa commented
Ping @BertVGroenendael, could you please check the comments from my colleagues @pedrobaeza and @juancarlosonate-tecnativa?

2025-03-26 14:54 UTC, carlos-lopez-tecnativa commented
Superseded by https://github.com/OCA/bank-payment/pull/1438

2025-03-26 14:59 UTC, closed without merging