Remove internal_type=other restriction for transfer account
OCA/bank-payment pull request #312
Opened 2016-11-13 16:01 UTC by jalzaga

module: account_payment_order
Related to issue: Cannot use type receivable or payable account as transfer account #309

2016-11-13 18:34 UTC, pedrobaeza requested changes

2016-11-13 18:34 UTC, pedrobaeza commented on account_payment_order/README.rst
> +* Angel Moya <angel.moya@domatix.com
The ending `>` is missing for both lines

2016-11-14 00:05 UTC, pedrobaeza approved these changes

2016-11-14 14:02 UTC, hbrunn approved these changes

2016-11-14 21:16 UTC, sbidoul approved these changes

2016-11-15 08:20 UTC, merged