[9.0][MIG]account_banking_mandate: Scritp migration to v9
OCA/bank-payment pull request #321
Opened 2016-12-09 23:47 UTC by sergio-teruel

cc @tecnativa

2016-12-09 23:54 UTC, pedrobaeza commented on account_banking_mandate/migrations/9.0.0.2.0/post-migration.py
> +    UPDATE account_move_line aml SET mandate_id = (
Please use compact form that saves one query:
```
UPDATE account_move_line aml 
SET mandate_id = ai.mandate_id
FROM account_invoice ai
WHERE aml.invoice_id=ai.id 
AND aml.invoice_id is not null
```

2016-12-09 23:55 UTC, pedrobaeza requested changes
Version folder should be 9.0.1.0.0

2016-12-09 23:57 UTC, sergio-teruel commented
@pedrobaeza changes done

2016-12-10 00:03 UTC, pedrobaeza commented on account_banking_mandate/migrations/9.0.1.0.0/post-migration.py
> +    AND aml.invoice_id is not null;
I'm thinking that you should also add `AND aml.mandate_id IS NOT NULL` for avoiding extra operations.

2016-12-10 00:07 UTC, sergio-teruel commented
@pedrobaeza changes done

2016-12-10 00:15 UTC, pedrobaeza approved these changes

2016-12-22 16:35 UTC, carlosdauden approved these changes

2016-12-22 16:37 UTC, merged