[9.0][MIG] account_payment_order: Migration script
OCA/bank-payment pull request #325
Opened 2016-12-16 12:54 UTC by sergio-teruel

WIP
cc @tecnativa

2016-12-16 13:34 UTC, pedrobaeza requested changes

2016-12-16 13:34 UTC, pedrobaeza commented on account_payment_order/migrations/9.0.1.1.1/pre-migration.py
> +    UPDATE ir_module_module SET state='to install' WHERE name in %s
I think this is automatically handled by OpenUpgrade. Please check and remove if so. If not, please include the condition that they are in state='uninstalled' (they can be already installed in the source database).

2016-12-16 13:34 UTC, pedrobaeza commented on account_payment_order/migrations/9.0.1.1.1/pre-migration.py
> +    ]
De-indent this line

2016-12-16 13:34 UTC, pedrobaeza commented on account_payment_order/migrations/9.0.1.1.1/pre-migration.py
> +# V9 modules that are not exist in v8 and are dependent of
s/that are not exist/that don't exist

2016-12-16 13:34 UTC, pedrobaeza commented on account_payment_order/migrations/9.0.1.1.1/pre-migration.py
> +    openupgrade.rename_tables(env.cr, table_renames)
Please use a function that I have just discovered that is more complete (also handles attachments and so on) and that applies here, as we are not renaming to None, but to a still useful table: _rename_models_ - https://github.com/OCA/openupgradelib/blob/c723fa4ccf288184d163d9daa211c3dc1281c263/openupgradelib/openupgrade.py#L362

2016-12-16 13:34 UTC, pedrobaeza commented on account_payment_order/migrations/9.0.1.1.1/post-migration.py
> +        'payment_order_type', 'payment_type',
Both fields exists in new module?

2016-12-27 08:49 UTC, pedrobaeza commented
Travis is red

2016-12-27 09:24 UTC, sergio-teruel commented
@pedrobaeza Changes done

2016-12-27 18:15 UTC, pedrobaeza approved these changes

2016-12-27 18:16 UTC, pedrobaeza commented
Merging optimistically as OpenUpgrade's policy.

2016-12-27 18:16 UTC, merged