[FIX] Bug #353 crash when selecting a payment mode that has a variable link to bank accounts
OCA/bank-payment pull request #354
Opened 2017-04-04 21:29 UTC by alexis-via

Cf bug #353 for a detailed scenario of the crash.

I you have better ideas to fix this bug, please propose. I suggests this solution because it's the only one I found that currently works on v10.

2017-04-05 07:22 UTC, pedrobaeza requested changes

2017-04-05 07:22 UTC, pedrobaeza commented on account_payment_order/models/account_payment_order.py
> +            'journal_id': "[('id', '=', False)]",
This should be `{'journal_id': []}`

2017-04-06 11:01 UTC, sbidoul commented
@alexis-via I think the onchange will not trigger when opening a previously saved payment order, so in that case, the domain will be wrong.

Dynamic domains are a pain to get right...

I think it's part of the reasons that pushed @lmignon to create https://github.com/OCA/web/pull/567. You may want to try it.

2017-04-06 12:28 UTC, alexis-via commented
@sbidoul Very interesting, thanks !
Another interesting bug report https://github.com/odoo/odoo/issues/16072

2017-05-16 08:12 UTC, alexis-via commented on account_payment_order/models/account_payment_order.py
> +            'journal_id': "[('id', '=', False)]",
If I make your modification, then I have access to all journals when no payment mode is selected, which is not what I want : I want the user to select a payement mode first. So I prefer my solution, which works well.

2017-05-16 08:13 UTC, alexis-via commented
I propose to merge this to avoid the crash. And then, if someone is able to propose a better solution, he will propose another PR.
I don't want to leave an horrible crash like this one too long in an important OCA module.

2017-05-16 08:45 UTC, sbidoul approved these changes

2017-05-16 09:02 UTC, pedrobaeza commented on account_payment_order/models/account_payment_order.py
> +            'journal_id': "[('id', '=', False)]",
Then please hide the field when no payment mode is selected in the view via `attrs` attribute.

2017-05-20 08:47 UTC, merged