[10.0] Add 'post_move' option on account.payment.mode
OCA/bank-payment pull request #363
Opened 2017-05-16 20:21 UTC by alexis-via

If you use account_cancel, it's not a problem to auto-post account moves generated upon final validation of the payment order, but for those who don't/can't use account_cancel, it's not a good idea to auto-post account moves.

2017-05-16 20:23 UTC, alexis-via commented
And posting account moves was not the default option in the banking modules for v8: https://github.com/OCA/bank-payment/blob/8.0/account_banking_payment_transfer/model/account_payment.py#L258
Now, we have the choice in v10 too (the option "entry_posted" doesn't exist any more on the journal).

2017-05-16 20:29 UTC, sbidoul approved these changes
+1

2017-05-16 23:13 UTC, pedrobaeza requested changes
Several things:

* Change module version number
* Put default=True for not changing behavior on a stable version.

2017-05-17 08:42 UTC, pedrobaeza approved these changes

2017-05-20 08:46 UTC, merged