[9.0][IMP] account_banking_mandate: Improve / fixes
OCA/bank-payment pull request #378
Opened 2017-08-02 09:48 UTC by carlosdauden

Adds a compute field in res.partner to search first valid mandate respecting partner banks order.
Fix payment_mode_id_change to set valid mandate if required
 
@Tecnativa

2017-08-02 16:19 UTC, pedrobaeza requested changes
We need to dig deeper in the onchange tough

2017-08-02 16:19 UTC, pedrobaeza commented on account_banking_mandate/models/res_partner.py
> +        string='Valid Mandate')
First Valid Mandate

2017-08-02 16:19 UTC, pedrobaeza commented on account_banking_mandate/models/res_partner.py
> +        # Dict to reduce impact with "bug" that process all partners related
`Dict for reducing the duplicated searches on parent/child partners`

2017-08-02 16:19 UTC, pedrobaeza commented on account_banking_mandate/models/res_partner.py
> +            commercial_partner_id = partner.commercial_partner_id
Name it `commercial_partner`

2017-08-02 16:19 UTC, pedrobaeza commented on account_banking_mandate/models/res_partner.py
> +                mandate_id = partner.commercial_partner_id.bank_ids.mapped(
This  is incorrect if you have more than one bank account or more than one valid mandate. It should be:
```
mandate_id = partner.commercial_partner_id.mapped('bank_ids.mandate_ids')..filtered(lambda x: x.state == 'valid')[:1].id
```

2017-08-24 17:07 UTC, rafaelbn commented
Hi @pedrobaeza , @carlosdauden attend you comments. Please review again. Thanks

2018-03-13 14:46 UTC, pedrobaeza commented
@carlosdauden is this still relevant?

2019-01-29 15:36 UTC, closed without merging