[MIG] portal_payment_mode: Migration to 9.0
OCA/bank-payment pull request #387
Opened 2017-09-05 07:42 UTC by chienandalu

Portal Payment Mode
===================

This module extends the functionality of *account_payment_partner* module to
allow to portal users view theirs invoices adding security permissions to
payment mode model.

cc @Tecnativa

2017-09-08 08:01 UTC, pedrobaeza requested changes

2017-09-08 08:01 UTC, pedrobaeza commented on portal_payment_mode/__openerp__.py
>      'author': 'Antiun Ingeniería S.L., '
Please remove old brands

2017-09-08 08:01 UTC, pedrobaeza commented
And check Travis status

2017-09-12 10:11 UTC, chienandalu commented
@pedrobaeza Changes done

2017-09-14 00:39 UTC, pedrobaeza approved these changes

2017-09-14 00:39 UTC, pedrobaeza commented
@luismontalba please review

2017-09-14 07:30 UTC, luismontalba approved these changes
Tested on runbot

2017-09-14 07:39 UTC, merged