[11.0 mig account payment order
OCA/bank-payment pull request #401
Opened 2017-10-11 15:00 UTC by etobella

2017-10-18 08:39 UTC, rgarnau reviewed
LGTM :+1: (minor comments inline)

2017-10-18 08:39 UTC, rgarnau commented on account_payment_order/README.rst
> +This module adds several options on Payment Modes, cf Accounting > Configuration > Management > Payment Modes.
'Invoicing' instead of 'Accounting'

2017-10-18 08:39 UTC, rgarnau commented on account_payment_order/README.rst
> +You can create a Payment Order via the menu Accounting > Payments > Payment Orders and then select the move lines to pay.
Invoicing

2017-10-18 08:39 UTC, rgarnau commented on account_payment_order/README.rst
> +You can create a Debit Order via the menu Accounting > Payments > Debit Orders and then select the move lines to debit.
Invoicing

2017-10-18 08:39 UTC, rgarnau commented on account_payment_order/README.rst
> +You can print a Payment Order via the menu Accounting > Payments > Payment Orders and then select the payment oder to print.
Invoicing

2017-10-18 11:24 UTC, rgarnau approved these changes

2017-10-27 15:26 UTC, jbeficent commented on account_payment_order/wizard/account_payment_line_create.py
> +                ('account_id.internal_type', '=', 'receivable'),
My concern with payment.orders is that it does not seem to be able to handle refunds. So, in the scenario where you have an angry customer that expects a refund (and is not likely to come again - so little chance to reconcile the refund in the future with a new invoice), you cannot create a payment order, due to this added domain. 

IMHO what should only matter here is that with inbound payment orders you pay debit > 0, for receivables and payables, and with outbound payment orders you pay credit > 0, for receiv & payab.

2017-11-03 14:15 UTC, JordiBForgeFlow approved these changes
:+1: Technical and functional review.

2017-11-07 15:16 UTC, HviorForgeFlow requested changes

2017-11-07 15:16 UTC, HviorForgeFlow commented on account_payment_order/README.rst
> +You can print a Payment Order via the menu Invoicing/Accounting > Payments > Payment Orders and then select the payment oder to print.
order

2017-11-07 15:16 UTC, hveficent commented on account_payment_order/models/account_invoice.py
> +                    "The invoice %s has a payment mode '%s' "
no string formatting:
"which is not selectable in payment orders.") % (inv.number, inv.payment_mode_id.display_name))

2017-11-07 16:00 UTC, HviorForgeFlow approved these changes
LGTM :+1:

2017-11-11 10:03 UTC, angelmoya commented
:+1:

2017-11-16 11:37 UTC, merged