[ADD] Bank name and bic to report_invoice
OCA/bank-payment pull request #423
Opened 2017-11-28 11:10 UTC by TDu

In account_payment_partner on the account invoice report.
Adds the bank name and BIC next to the existing account number.

2017-11-28 11:20 UTC, pedrobaeza commented
Why the CDATA?

2017-11-28 11:21 UTC, TDu commented
@pedrobaeza I thought they where needed to give space between fields ?
But I am probably mistaken.

2017-11-28 11:27 UTC, TDu commented
Indeed I was. I just removed them.

2017-11-28 12:27 UTC, pedrobaeza requested changes
I prefer to save a line on this putting something like:

`BANK NAME (BIC)`

and having into account that sometimes the BIC is not set.

And please change module version number, while we are discussing about the bot that makes it automatically.

2017-11-28 15:55 UTC, TDu commented
I have change the version number.
I am not sure I understand your preference about saving a line ?

2017-11-28 15:59 UTC, pedrobaeza commented
I'm saying not to put 2 `t-field`, but a t-esc like:
```
<t t-esc="o.partner_bank_id.bank_id.name + ('' if not o.partner_bank_id.bank_id.bic else ' (' + o.partner_bank_id.bank_id.bic + ')')"/>
```

2017-11-30 12:55 UTC, fclementic2c commented
:+1:

2017-11-30 16:13 UTC, pedrobaeza approved these changes

2017-12-11 12:16 UTC, merged