[10.0][MIG] payment killer migration
OCA/bank-payment pull request #480
Opened 2018-05-31 01:37 UTC by ovnicraft

migration include move xml to new directories: view an security

2018-06-07 23:48 UTC, ovnicraft commented
any review here ?

2018-06-07 23:51 UTC, pedrobaeza requested changes

2018-06-07 23:51 UTC, pedrobaeza commented on account_voucher_killer/view/invoice_view.xml
> +<openerp>
Use Odoo

2018-06-07 23:51 UTC, pedrobaeza commented on account_voucher_killer/view/invoice_view.xml
> +  <data>
Remove this unneeded tag

2018-06-08 16:27 UTC, ovnicraft commented
@pedrobaeza Done

2018-06-08 16:32 UTC, pedrobaeza approved these changes

2018-06-09 19:44 UTC, MeetKD requested changes

2018-06-09 19:44 UTC, MeetKD commented on account_voucher_killer/__manifest__.py
>   'website': 'http://www.camptocamp.com',
Change `'website' : https://github.com/OCA/bank-payment`
May be you should define a meaningful category.

2018-06-09 19:44 UTC, MeetKD commented on account_voucher_killer/view/invoice_view.xml
> +      <field name="name">Hide voucher in invoice</field>
Hide payment in...

2018-06-11 13:46 UTC, ovnicraft commented
@MeetKD done

2018-06-20 02:56 UTC, ovnicraft commented
@MeetKD can you review it please ?

2018-06-22 17:52 UTC, MeetKD approved these changes

2018-06-22 17:56 UTC, merged