[12.0] [MIG] account_payment_purchase
OCA/bank-payment pull request #537
Opened 2019-01-19 11:33 UTC by Nikul-Chaudhary

Account Payment Purchase
========================
This module adds 2 fields on purchase orders: *Bank Account* and *Payment Mode*. These fields are copied from partner to purchase order and then from purchase order to supplier invoice.

This module is similar to the *purchase_payment* module; the main difference is that it doesn't depend on the *account_payment_extension* module (it's not the only module to conflict with *account_payment_extension*; all the SEPA modules in the banking addons conflict with *account_payment_extension*).

2019-01-19 14:19 UTC, pedrobaeza commented
Please sign the CLA and check runbot and Travis status.

2019-01-20 05:22 UTC, Nikul-Chaudhary commented
> Please sign the CLA and check runbot and Travis status.

@pedrobaeza I already sent mail `cla@odoo-community.org & info@odoo-community.org`

Can you please check and Process for that. Thanks.


![screenshot from 2019-01-20 10-50-15](https://user-images.githubusercontent.com/43105931/51435618-6e753c00-1ca1-11e9-827f-593f5f2b41d0.png)

2019-01-20 11:27 UTC, pedrobaeza requested changes

2019-01-20 11:27 UTC, pedrobaeza commented on account_payment_purchase/__manifest__.py
> +        'stock',
You have to depend from `purchase_stock`, as you are using data from it.

2019-01-20 17:53 UTC, Nikul-Chaudhary commented
@pedrobaeza Done!

2019-01-20 18:07 UTC, pedrobaeza approved these changes

2019-02-06 18:54 UTC, Nikul-Chaudhary commented
@OCA/banking-maintainers Could you please review it?

2019-03-18 18:56 UTC, MiquelRForgeFlow approved these changes
code review LGTM

2019-03-19 03:14 UTC, merged