[FIX] 12.0 make account_payment_order_inbound test multicompany resilient
OCA/bank-payment pull request #682
Opened 2020-02-27 09:14 UTC by PieterPaulussen

@pedrobaeza Since you were the last person to update these tests, I would appreciate a small review.
In a multicompany setup, the search results on `account.journal` are not accurate enough because the record rules do not apply to the superuser.

2020-03-03 13:24 UTC, pedrobaeza commented
It's very difficult to understand the problem if you mix stylistic changes with the real ones. Please restore again the `self = cls` line and let `self`, although I know that's not the best idiomatic, but it was done the same for reducing the diff (TransactionCase was switched to SavepointCase for increasing performance). If you want still to apply that change, at least do it in a separate commit.

When done, I will come back and check.

2020-03-04 10:55 UTC, PieterPaulussen commented
@pedrobaeza Thanks for the feedback, I split the changes into 2 separate commits as you suggested

2020-03-04 12:50 UTC, pedrobaeza approved these changes
Perfect, thanks

2020-03-04 12:51 UTC, pedrobaeza requested changes
Oh, not so perfect. Please don't undo the split in 2 classes: Base and the other. You are breaking the inheritability of that class for using in other modules tests.

2020-03-04 12:52 UTC, pedrobaeza commented
Example of something that you have broken:

https://github.com/OCA/account-reconcile/blob/f93f6d6415e60959c60565c190f5d7911a8e8cde/account_reconcile_payment_order/tests/test_account_reconcile_payment_order.py#L5

and not only that, this is done on purpose for not repeating the tests in the inherited test.

2020-03-04 15:54 UTC, PieterPaulussen commented
I was unaware of the usage of that base case. Stupid of me not to check.

2020-03-04 16:22 UTC, pedrobaeza approved these changes
It's a good habit any way to split your tests in 2 classes if others can reuse your setup: one base with that setup, and another for the tests themselves.

2020-03-05 08:32 UTC, PieterPaulussen commented
@pedrobaeza Found another little snag during the tests [here](https://github.com/OCA/bank-payment/pull/682/files#diff-de4893858393574c4b1e0d1038cd93afR24) and [here](https://github.com/OCA/bank-payment/pull/682/files#diff-de4893858393574c4b1e0d1038cd93afR30-R34) . The installation of the demo data adds all existing journals and ignores the addition of the domain defined on the field definition of `default_journal_ids`. There are 2 possible solutions of course. Either specify the journals with a domain on the main company or just update it in the tests. I chose the second because it seemed trivial.

2020-03-05 08:35 UTC, pedrobaeza commented
I don't get the problem, but I see problematic to remove the company from the demo data.

2020-03-05 08:55 UTC, PieterPaulussen commented
I believe these domains [here](https://github.com/OCA/bank-payment/blob/12.0/account_payment_order/demo/payment_demo.xml#L23) and [here](https://github.com/OCA/bank-payment/blob/12.0/account_payment_order/demo/payment_demo.xml#L28) don't take into account the default domain defined on the field [here](https://github.com/OCA/bank-payment/blob/12.0/account_payment_order/models/account_payment_mode.py#L33)
Given a standard installation where you just have 1 company and install this module, this will always work. But when multiple companies are already setup, all journals including those from other companies are included. This leads to the problem where moves are selected outside of the current user company for which payment orders are generated for.

2020-03-05 15:55 UTC, pedrobaeza commented
Then I think the patch is to include in the search also the main_company as part of that domain.

2020-04-15 19:08 UTC, PieterPaulussen commented
@pedrobaeza Updated the domain as well. Feel free to review my changes again. Thanks!

2020-04-16 07:16 UTC, pedrobaeza approved these changes
Thanks for the work!

2020-04-16 07:31 UTC, carlosdauden approved these changes

2020-04-16 07:33 UTC, pedrobaeza commented
/ocabot merge minor

2020-04-16 08:09 UTC, merged