[FIX] 10.0 - prevent partner_bank_id to stay undefined
OCA/bank-payment pull request #725
Opened 2020-08-13 10:19 UTC by lmarion-source

In some cases, mandate can exist without a partner_bank_id. In this case, local variable 'partner_bank_id' was never initialize, causing a bug. Now, 'partner_bank_id' is initialize to False

2020-08-13 10:30 UTC, astirpe requested changes

2020-08-13 10:30 UTC, astirpe commented on account_banking_mandate/models/account_move_line.py
> +        # Initilization of partner_bank_id
Typo:

```suggestion
        # Initialization of partner_bank_id
```

2020-08-13 10:44 UTC, astirpe commented on account_banking_mandate/models/account_move_line.py
> +        # Initilization of partner_bank_id
I think you can even remove this comment, as the code is self-explanatory

2020-08-14 13:11 UTC, sbidoul approved these changes
I'd remove the comment too. It is the kind of change that is best explained in the PR or commit message than a code comment.

2020-08-14 13:19 UTC, astirpe approved these changes

2020-08-14 13:20 UTC, astirpe commented
Could you squash the two commits together?

2020-08-14 13:35 UTC, sbidoul commented
/ocabot merge patch

2020-08-14 13:43 UTC, merged