[14.0] [MIG] account_banking_sepa_direct_debit: Migration to v14
OCA/bank-payment pull request #773
Opened 2021-01-14 08:12 UTC by CarlosRoca13

cc @Tecnativa TT26414

This PR superseds https://github.com/OCA/bank-payment/pull/763

Please, @joao-p-marques  @pedrobaeza can you review this?

2021-01-14 12:06 UTC, joao-p-marques approved these changes
Code review :+1: Just a small comment

Can you squash the administrative commits to reduce the commit noise?

2021-01-14 12:06 UTC, joao-p-marques commented on account_banking_sepa_direct_debit/models/account_banking_mandate.py
> -        for mandate in self:
Why removing this loop? Shouldn't you do the same for all the records if it is a multi record set? I can see that in another implementation of this it is done: https://github.com/OCA/bank-payment/blob/14.0/account_banking_mandate/models/account_banking_mandate.py#L189

2021-01-14 12:44 UTC, pedrobaeza commented on account_banking_sepa_direct_debit/models/account_banking_mandate.py
> -        for mandate in self:
onchanges are supposed to be always singleton. The loop doesn't hurt, but it's not needed as well.

2021-01-14 12:49 UTC, pedrobaeza requested changes

2021-01-14 12:49 UTC, pedrobaeza commented on account_banking_sepa_direct_debit/tests/__init__.py
> +# from . import test_sdd  # TODO port those tests
This file must be readded and fixed

2021-01-15 07:51 UTC, CarlosRoca13 commented
The model TestAccountMultiCompanyNoChartCommon has dissapeared on 14.0, so I recover the field and method definition used on this tests from 13.0. Please, @pedrobaeza can you review it again?

2021-01-24 12:28 UTC, pedrobaeza requested changes
Please rename the commit message accordingly the changes done.

Why the uncovered lines?

2021-01-24 12:28 UTC, pedrobaeza commented on account_banking_sepa_direct_debit/tests/test_sdd.py
> +        self.company_B = self.env["res.company"].create({"name": "Company B"})
The `self = cls` was a trick for not creating a big diff when the switch to SavepointCase was onde, but you shouldn't use `self` in new lines, and don't change it in existing ones. If any thing to do, is the contrary one:  change all existing `self` to `cls` and remove the alias.

2021-01-24 12:28 UTC, pedrobaeza commented on account_banking_sepa_direct_debit/tests/test_sdd.py
> +        cls.journal_purchase = cls.env["account.journal"].create(
I don't think all these journals are really needed here.

2021-02-08 09:16 UTC, CarlosRoca13 commented
@pedrobaeza I removed the not needed journals and `self = cls` alias.

2021-02-08 19:25 UTC, pedrobaeza approved these changes

2021-02-08 19:25 UTC, pedrobaeza commented
/ocabot merge nobump

2021-02-08 19:38 UTC, merged