[ADD][14.0] account_payment_order_void_lines Module.
OCA/bank-payment pull request #777
Opened 2021-01-29 07:01 UTC by Murtaza-OSI

2021-03-07 21:49 UTC, max3903 commented
@Murtaza-OSI 

```
<string>:1: (WARNING/2) Title overline too short.

=====================
Account Payment Order Void Lines
=====================
2021-03-07 21:40:42,461 218 WARNING odoodb odoo.addons.base.models.ir_module: docutils' system message present: <system_message level="2" line="1" source="<string>" type="WARNING"><paragraph>Title overline too short.</paragraph><literal_block xml:space="preserve">=====================
Account Payment Order Void Lines
=====================</literal_block></system_message>
```

2021-03-08 07:15 UTC, pedrobaeza commented
Please avoid plurals in module name.

2021-09-28 13:58 UTC, dreispt commented on account_payment_order_void_lines/README.rst
> +Installation
Can we instead use the `readme/` subdirectory with readme fragments?

2021-11-09 09:47 UTC, dreispt requested changes
[ ]  Change module name to account_payment_order_void_lines
[ ] Add readme/ subdirectory with readme fragments

2022-02-24 14:53 UTC, dreispt reviewed
Please remove the OSI icon, OCA modules can't be company branded.

2022-02-24 14:53 UTC, dreispt commented on account_payment_order_void_line/readme/USAGE.rst
> +This module is used to cancel the payment line.
How?
Can you describe the steps to use or test this?

2022-11-15 11:35 UTC, dreispt approved these changes

2023-04-23 12:13 UTC, closed without merging