[15.0][MIG]account_banking_mandate
OCA/bank-payment pull request #914
Opened 2022-04-07 10:08 UTC by manuelregidor

Supersedes https://github.com/OCA/bank-payment/pull/883

2022-04-07 10:14 UTC, manuelregidor commented
@ValentinVinagre @HaraldPanten

2022-04-07 10:36 UTC, HaraldPanten commented
/ocabot migration account_banking_mandate

2022-04-07 10:53 UTC, HaraldPanten commented
@MiquelRForgeFlow @pedrobaeza

2022-04-08 11:15 UTC, HaraldPanten approved these changes
Functional review 👍

2022-04-08 14:47 UTC, ValentinVinagre approved these changes
LGTM 👍🏻

2022-04-12 09:58 UTC, ValentinVinagre requested changes
Adapt the tests please.

2022-04-12 09:58 UTC, ValentinVinagre commented on account_banking_mandate/tests/test_invoice_mandate.py
> +        # pay_method_test = self.env["account.payment.method"].create(
See here one example: https://github.com/odoo/odoo/blob/756b571d3bc72d47f9cf952d28e9765d1192dc39/addons/payment/tests/common.py#L21

2022-04-12 10:41 UTC, ValentinVinagre commented on account_banking_mandate/tests/test_invoice_mandate.py
> +        # pay_method_test = self.env["account.payment.method"].create(
Perfect, thanks 😄

2022-04-12 10:42 UTC, ValentinVinagre approved these changes
LGTM 👍🏻

2022-04-12 11:07 UTC, HaraldPanten commented
/ocabot merge nobump

2022-04-12 11:13 UTC, merged