[WIP][ADD] account_payment_order_sequence_payment_mode
OCA/bank-payment pull request #954
Opened 2022-08-24 13:23 UTC by xavier-bouquiaux

2022-08-25 07:38 UTC, acsonefho requested changes

2022-08-25 07:38 UTC, acsonefho commented on account_payment_order_sequence_payment_mode/models/account_payment_mode.py
> +    sequence_payment_order = fields.Many2one(
Should be `sequence_payment_order_id` (+ related changes)

2022-08-25 07:38 UTC, acsonefho commented on account_payment_order_sequence_payment_mode/models/account_payment_order.py
> +                self.env["account.payment.mode"].browse(mode_id).sequence_payment_order
Missing readme for this module.

2022-08-31 06:38 UTC, acsonefho requested changes

2022-08-31 06:38 UTC, acsonefho commented on account_payment_order_sequence_payment_mode/views/account_payment_mode.xml
> +                    name="sequence_payment_order"
You forgot to rename the field in the view

2022-08-31 13:27 UTC, acsonefho approved these changes

2022-09-20 12:00 UTC, adrienpeiffer approved these changes

2022-09-20 12:01 UTC, adrienpeiffer commented
/ocabot merge nobump

2022-09-20 12:11 UTC, merged