[16.0] [MIG] account_payment_partner
OCA/bank-payment pull request #969
Opened 2022-10-11 12:27 UTC by ThomasBinsfeld

2022-10-11 12:59 UTC, adrienpeiffer commented
/ocabot migration account_payment_partner

2022-10-25 08:04 UTC, marylla commented
> Needs #968

@ThomasBinsfeld PR #968 is merged now. Could you please rebase this PR? I'd like to test it in runboat.

2022-11-10 13:47 UTC, atchuthan requested changes
Except the view error, other functionalities tested :+1:

2022-11-10 13:47 UTC, atchuthan commented on account_payment_partner/views/account_move_line.xml
> +                expr="//field[@name='analytic_distribution_stored_char']/.."
Getting error with this Xpath
Change it to 
```
            <xpath
                expr="//group[@groups='analytic.group_analytic_accounting']"
                position="after"
            >
```

Error detail
```
Element '<xpath expr="//field[@name=&#39;analytic_distribution_stored_char&#39;]/..">' cannot be located in parent view

View error context:
{'file': '/opt/odoo/appstest16-odoo/src/OCA/bank-payment/account_payment_partner/views/account_move_line.xml',
 'line': 2,
 'name': 'account_payment_partner.move_line_form',
 'view': ir.ui.view(2118,),
 'view.model': 'account.move.line',
 'view.parent': ir.ui.view(568,),
 'xmlid': 'view_move_line_form'}
```

2022-11-17 14:41 UTC, etobella commented
@ThomasBinsfeld can you rebase?

2022-11-17 15:04 UTC, ThomasBinsfeld commented
> @ThomasBinsfeld can you rebase?

Done

2022-11-17 17:30 UTC, etobella commented
Tests are failing due to some problems with a view. Can you check it?

2022-11-17 17:32 UTC, etobella commented
This should fix pre-commit #989

2022-11-29 12:28 UTC, florian-dacosta commented
Hello @ThomasBinsfeld could you fix the view issue and make a new rebase ?
If needed, I can superseed this PR to make the changes, you let me know

2022-11-29 13:52 UTC, ThomasBinsfeld commented
> Hello @ThomasBinsfeld could you fix the view issue and make a new rebase ? If needed, I can superseed this PR to make the changes, you let me know

Fixed

2022-12-05 18:54 UTC, pere-aquarian approved these changes

2022-12-06 12:35 UTC, atchuthan approved these changes

2022-12-06 14:45 UTC, pedrobaeza commented
/ocabot migration account_payment_partner
/ocabot merge nobump

2022-12-06 14:51 UTC, merged